DROP SEQUENCE dim_member_seq;
DROP SEQUENCE dim_date_seq;
DROP SEQUENCE dim_facility_seq;
DROP SEQUENCE dim_book_seq;

CREATE SEQUENCE dim_member_seq 
START WITH 100001 
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE dim_date_seq 
START WITH 100001
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE dim_facility_seq 
START WITH 100001
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE dim_book_seq 
START WITH 100001
INCREMENT BY 1
NOCACHE;